### ISSUE TITLE
Question about variance minimization using noise schedule

### ISSUE THREAD

**Issue by pjh4993** [google-research/vdm#1]
Thank you for your great work and open-sourcing the code.
I have question about variance minimization using noise schedule explained on supplementary I.2 section.

![1655721394](https://user-images.githubusercontent.com/12472082/174584111-be88220f-a74b-4c4d-9a65-a0fd45f7e276.png)

Which part of code corresponds to this optimization?

Thanks,
pjh

**Comment by Skylion007** [comment]
@pjh4993 Did you ever find where this is implemented in the codebase?

**Comment by pjh4993** [comment]
> @pjh4993 Did you ever find where this is implemented in the codebase?

Not sure about current version, but at that time I couldn't find this.

I'm pretty much sure that this repo only contains training procedure for parameteric noise scheduler.

**Comment by Skylion007** [comment]
Yeah, we came to the same conclusion.
